### ISSUE TITLE
Error in 01.-basics-extra (Schödingers bug)

### ISSUE THREAD

**Issue by MichielStock** [Beramos/DS-Julia2925#75] opened 2021-02-03 12:36 UTC
![Screen Shot 2021-02-03 at 13 36 02](https://user-images.githubusercontent.com/6018979/106747886-c4b53d80-6624-11eb-808f-8b61ed2fc6a8.png)

Is this normal, @DaanVanHauwermeiren ?

**Comment by Beramos** [comment] 2021-02-03 12:38
Ik heb die ook

Op wo 3 feb. 2021 13:37 schreef Michiel Stock <notifications@github.com>:

**Comment by DaanVanHauwermeiren** [comment] 2021-02-03 13:51
Could not reproduce the issue, I did:

```
mdkir TMP
git clone https://github.com/Beramos/DS-Julia2925.git
cd TMP
# source julia env
julia launch.jl
# open basics extra
```

Can you provide exact reproduction instructions?

**Comment by Beramos** [comment] 2021-02-03 13:53
Wat is je Julia versie?

Op wo 3 feb. 2021 14:52 schreef DaanVanHauwermeiren <
notifications@github.com>:

**Comment by DaanVanHauwermeiren** [comment] 2021-02-03 13:54
1.5.0

**Comment by DaanVanHauwermeiren** [comment] 2021-02-03 14:02
just tested with Version 1.5.3 (2020-11-09)
Works just fine

**Comment by Beramos** [comment] 2021-02-03 16:21
Check I tested it again, now it works fine. What a strange bug.

**Comment by Beramos** [comment] 2021-02-03 16:22
I will close it for now although it is still rather :fish:y

**Closed by Beramos** 2021-02-03 16:22 UTC
